{{- if .Values.eventBusConnector.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: event-bus-connector-config
data:
  connect-standalone.properties: |
     bootstrap.servers = event-bus-service.default.svc.cluster.local:9092
     key.converter=org.apache.kafka.connect.json.JsonConverter
     value.converter=org.apache.kafka.connect.json.JsonConverter
     key.converter.schemas.enable=false
     value.converter.schemas.enable=false
     offset.storage.file.filename=/tmp/connect.offsets
     offset.flush.interval.ms=10000
     plugin.path=/opt/bitnami/kafka/plugins
  postgres.properties: |
    connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
    connection.url=jdbc:postgresql://database-service.default.svc.cluster.local:5432/database_smart_home
    connection.user=event_bus_connector
    connection.password=password
    tasks.max=1
    table.name.format=schema_smart_home.${topic}
    auto.create=true
    auto.evolve=true
    name=kafka-postgres-sink-connector
    pk.mode=none
    delete.enabled=false  
    key.converter=org.apache.kafka.connect.json.JsonConverter
    value.converter=org.apache.kafka.connect.json.JsonConverter
    errors.log.enable = true
    errors.log.include.messages = true
    topics.regex = ^TOPIC.*
{{- end }}