{{- if .Values.database.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database.sql: |
        CREATE DATABASE db_smart_home;
        \c db_smart_home;
        CREATE SCHEMA s_smart_home;
        CREATE USER {{ .Values.eventBusConnector.dbUser }} WITH PASSWORD '{{ .Values.eventBusConnector.dbUserPassword }}';
        GRANT CONNECT ON DATABASE db_smart_home TO {{ .Values.eventBusConnector.dbUser }};
        GRANT USAGE ON SCHEMA s_smart_home TO {{ .Values.eventBusConnector.dbUser }};
        GRANT CREATE ON SCHEMA s_smart_home TO {{ .Values.eventBusConnector.dbUser }};
{{- end }}