{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database-container
          image: {{ .Values.database.image }}
          ports:
            - containerPort: {{ .Values.database.port }}
          env:
            - name: POSTGRES_PASSWORD
              value: {{ .Values.database.password }}
          volumeMounts:
            - name: database-config
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: database-config
          configMap:
            name: database-config
{{- end }}