{{- if .Values.database.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - name: database
      protocol: TCP
      port: {{ .Values.dbconf.dbPort }}
      targetPort: {{ .Values.dbconf.dbPort }}      
{{- end }}