{{- if .Values.database.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  database.sql: |
        CREATE DATABASE db_smart_home;
        \c db_smart_home;
        CREATE SCHEMA s_smart_home;
        CREATE USER event_bus_connector WITH PASSWORD 'password';
        GRANT CONNECT ON DATABASE db_smart_home TO event_bus_connector;
        GRANT USAGE ON SCHEMA s_smart_home TO event_bus_connector;
        GRANT CREATE ON SCHEMA s_smart_home TO event_bus_connector;
{{- end }}