apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-config
data:
  connect-standalone.properties: |
     bootstrap.servers = event-bus-service.default.svc.cluster.local:9092
     key.converter=org.apache.kafka.connect.json.JsonConverter
     value.converter=org.apache.kafka.connect.json.JsonConverter
     key.converter.schemas.enable=true
     value.converter.schemas.enable=true
     offset.storage.file.filename=/tmp/connect.offsets
     offset.flush.interval.ms=10000
     plugin.path=/opt/bitnami/kafka/plugins
  postgres.properties: |
    # PostgreSQL connector configuration

    # Connector class
    connector.class=io.confluent.connect.jdbc.JdbcSinkConnector
    connection.url=jdbc:postgresql://database-service.default.svc.cluster.local:5432/smart_home
    connection.user=postgres
    connection.password=password
    topics=connected_components_updates

    # Number of tasks
    tasks.max=1

    # Name of the table to write to
    table.name.format=connected_components_updates

    # Set to true to create the table if it doesn't exist
    auto.create=true

    # Set to true to drop the table if it already exists
    auto.evolve=true

    # Unique name for the connector instance
    name=my-postgres-connector
