# templates/consumer-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - name: consumer-container
          image: {{ .Values.consumer.image }}
          ports:
            - containerPort: {{ .Values.consumer.port }}
