# database-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  selector:
    app: database
  ports:
    - name: database
      protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}