{{- if .Values.dbImporter.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-importer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-importer
  template:
    metadata:
      labels:
        app: db-importer
    spec:
      imagePullSecrets:
      - name: registry-credentials
      containers:
        - name: db-importer-container
          image: "{{ .Values.registryConf.registry }}{{ .Values.dbImporter.image }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_PASS
              value: {{ .Values.rabbitmq.pass }}
            - name: DB_HOST
              value: "{{ .Values.dbconf.dbHost }}"
            - name: DB_PORT
              value: "{{ .Values.dbconf.dbPort }}"
            - name: DB_NAME
              value: {{ .Values.dbconf.dbName }}
            - name: DB_USER
              value: {{ .Values.dbconf.dbUser }}
            - name: DB_PASSWORD
              value: {{ .Values.dbconf.dbUserPassword }}
            - name: DB_SCHEMA
              value: {{ .Values.dbconf.dbSchema }}
{{- end }}