{{- if .Values.eventBusConnector.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-connector-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus-connector-server
  template:
    metadata:
      labels:
        app: event-bus-connector-server
    spec:
      hostname: {{ .Values.eventBusConnector.hostname }}
      containers:
        - name: event-bus-connector-server-container
          command:
            - /bin/bash
            - -ec
            - |
              /opt/bitnami/kafka/bin/connect-standalone.sh /config/connect-standalone.properties /config/postgres.properties
          image: {{ .Values.eventBusConnector.image }}
          ports:
            - containerPort: {{ .Values.eventBusConnector.kafkaPort }}
            - containerPort: {{ .Values.eventBusConnector.controllerPort }}
            - containerPort: {{ .Values.eventBusConnector.connectorPort }}
          volumeMounts:
            - name: connector-config
              mountPath: /config
      volumes:
        - name: connector-config
          configMap:
            name: connector-config
{{- end }}
