{{- if .Values.lightBulbMonitor.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: light-bulb-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-bulb-monitor
  template:
    metadata:
      labels:
        app: light-bulb-monitor
    spec:
      imagePullSecrets:
        - name: registry-credentials
      containers:
        - name: light-bulb-monitor-container
          image: "{{ default "localhost:32000" .Values.registryConf.registry }}/{{ .Values.lightBulbMonitor.image }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_PASS
              value: {{ .Values.rabbitmq.pass }}
{{- end }}