{{- if .Values.lightBulbMonitor.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: light-bulb-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-bulb-monitor
  template:
    metadata:
      labels:
        app: light-bulb-monitor
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    spec:
      {{- if .Values.registryConf.registry }}
      imagePullSecrets:
        - name: registry-credentials
      {{- end }}
      containers:
        - name: light-bulb-monitor-container
          image: "{{ default "localhost:32000" .Values.registryConf.registry }}/{{ .Values.lightBulbMonitor.image }}"
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
            - containerPort: 8080
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_PASS
              value: {{ .Values.rabbitmq.pass }}
{{- end }}