{{- if .Values.producer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: {{ .Values.producer.port }}
      targetPort: {{ .Values.producer.port }}
{{- end }}