{{- if .Values.producer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer-container
          image: {{ .Values.producer.image }}
          ports:
            - containerPort: {{ .Values.producer.port }}
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.producer.bootstrapServers }}
            - name: GROUP_ID
              value: "{{ .Values.producer.groupId }}"
            - name: TOPIC
              value: {{ .Values.producer.topic }}
{{- end }}