apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: rabbitmq
    port: {{ .Values.rabbitmq.port }}
    targetPort: 5672
  - name: rabbitmq-management
    port: 15672
    targetPort: 15672
  - name: rabbitmq-prometheus
    port: 15692
    targetPort: 15692

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  replicas: 1
  volumeClaimTemplates: []
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: metadata.name
      containers:
      - name: rabbitmq
        image: {{ .Values.eventBus.image }}
        ports:
        - containerPort: 5672
        - containerPort: 15672
        - containerPort: 15692
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RABBITMQ_ERLANG_COOKIE
          value: "secretcookie"
        - name: K8S_SERVICE_NAME
          value: rabbitmq
        - name: RABBITMQ_NODENAME
          #value: rabbit@$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.cluster.local
          value: rabbit@$(MY_POD_NAME)
        volumeMounts:
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq/conf.d/
      volumes:
      - name: rabbitmq-config-volume
        configMap:
          name: rabbitmq-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
data:
  rabbitmq.conf: |
    #cluster_formation.peer_discovery_backend = classic_config
    #cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq-0.rabbitmq.default.svc.cluster.local
    #cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq-1.rabbitmq.default.svc.cluster.local
    #cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq-2.rabbitmq.default.svc.cluster.local
    
    #cluster_partition_handling = autoheal
    #queue_master_locator = min-masters
    loopback_users.guest = false
    log.console = true

