version: 2.1

parameters:
  param-build-db-importer:
    type: boolean
    default: false
  param-build-light-bulb:
    type: boolean
    default: false
  param-build-light-bulb-monitor:
    type: boolean
    default: false
jobs:
  build-db-importer:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: Docker login
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
      - run: 
          name: Build dbImporter
          command: |
            docker build -t "${DOCKER_REPO}:db-importer-latest" "java/dbImporter"
            docker push "${DOCKER_REPO}:db-importer-latest"
      - run:
          name: Extract artifact from Docker image - dbImporter
          command: |
            docker create --name temp_container_dbi ${DOCKER_REPO}:db-importer-latest
            docker cp temp_container_dbi:/app/jacoco /tmp/jacoco-dbImporter
            docker rm temp_container_dbi
            zip -r /tmp/jacoco-dbImporter.zip /tmp/jacoco-dbImporter
      - store_artifacts:
          path: /tmp/jacoco-dbImporter.zip
  build-light-bulb:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: Docker login
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
      - run: 
          name: Build light-bulb
          command: |
            docker build -t "${DOCKER_REPO}:light-bulb-latest" "java/lightBulb"
            docker push "${DOCKER_REPO}:light-bulb-latest"
      - run:
          name: Extract artifact from Docker image - light-bulb
          command: |
            docker create --name temp_container_lb ${DOCKER_REPO}:light-bulb-latest
            docker cp temp_container_lb:/app/jacoco /tmp/jacoco-lightBulb
            docker rm temp_container_lb
            zip -r /tmp/jacoco-lightBulb.zip /tmp/jacoco-lightBulb
      - store_artifacts:
          path: /tmp/jacoco-lightBulb.zip
  build-light-bulb-monitor:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: Docker login
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
      - run:
          name: Extract Code Coverage - light-bulb-monitor
          command: |
            docker build -t temp_build_lbm java/lightBulbMonitor
            docker create --name temp_container_lbm temp_build_lbm
            docker cp temp_container_lbm:/app/target/site/jacoco /tmp/jacoco-lightBulbMonitor
            docker rm temp_container_lbm
            zip -r /tmp/jacoco-lightBulbMonitor.zip /tmp/jacoco-lightBulbMonitor
      - store_artifacts:
          path: /tmp/jacoco-lightBulbMonitor.zip
      - run: 
          name: Build light-bulb-monitor
          command: |
            docker build -t "${DOCKER_REPO}:light-bulb-monitor-latest" "java/lightBulbMonitor"
            docker push "${DOCKER_REPO}:light-bulb-monitor-latest"
workflows:
  workflow-build-db-importer:
    when: << pipeline.parameters.param-build-db-importer >>
    jobs:
      - build-db-importer:
          context:
            - org-context-smart-home
  workflow-build-light-bulb:
    when: << pipeline.parameters.param-build-light-bulb >>
    jobs:
      - build-light-bulb:
          context:
            - org-context-smart-home
  workflow-build-light-bulb-monitor:
    when: << pipeline.parameters.param-build-light-bulb-monitor >>
    jobs:
      - build-light-bulb-monitor:
          context:
            - org-context-smart-home