# Name: continue_config.yml
# Description: Pipeline for circleci, continuing from config.yml
# Extracts code coverage metrics, builds the image, adds docs to github
# stores the image, stores the metrics as an artifact in circleci
# Author: ja-m3s
version: 2.1
parameters:
  param-build-shared-utils:
    type: boolean
    default: false
  param-build-db-importer:
    type: boolean
    default: false
  param-build-light-bulb:
    type: boolean
    default: false
  param-build-light-bulb-monitor:
    type: boolean
    default: false
  param-build-remote:
    type: boolean
    default: false

executors:
  build:
    machine:
      image: ubuntu-2204:current
      docker_layer_caching: true

jobs:
  build:
    executor: build
    parameters:
        docker-repo:
          type: string
        docker-file-location:
          type: string
    steps:
      - checkout
      - run:
          name: 'Build Docker image'
          command: |
            docker build -t "<< parameters.docker-repo >>:latest" -f "<< parameters.docker-file-location >>" "java"
      - run:
          name: 'Push to repository'
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            docker push "<< parameters.docker-repo >>:latest"

workflows:

  workflow-build-db-importer:
    when: << pipeline.parameters.param-build-db-importer >>
    jobs:
      - build:
          docker-repo: ${DOCKER_REPO_DB_IMPORTER}
          docker-file-location: "java/dbImporter/Dockerfile"
          context:
            - org-context-smart-home

  workflow-build-light-bulb:
    when: << pipeline.parameters.param-build-light-bulb >>
    jobs:
      - build:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB}
          docker-file-location: "java/lightBulb/Dockerfile"
          context:
            - org-context-smart-home

  workflow-build-light-bulb-monitor:
    when: << pipeline.parameters.param-build-light-bulb-monitor >>
    jobs:
      - build:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB_MONITOR}
          docker-file-location: "java/lightBulbMonitor/Dockerfile"
          context:
            - org-context-smart-home

  workflow-build-remote:
    when: << pipeline.parameters.param-build-remote >>
    jobs:
      - build:
          docker-repo: ${DOCKER_REPO_REMOTE}
          docker-file-location: "java/remote/Dockerfile"
          context:
            - org-context-smart-home
