# Name: continue_config.yml
# Description: Pipeline for circleci, continuing from config.yml
# Extracts code coverage metrics, builds the image, adds docs to github
# stores the image, stores the metrics as an artifact in circleci
# Author: ja-m3s
version: 2.1
parameters:
  param-build-shared-utils:
    type: boolean
    default: false
  param-build-db-importer:
    type: boolean
    default: false
  param-build-light-bulb:
    type: boolean
    default: false
  param-build-light-bulb-monitor:
    type: boolean
    default: false
  param-build-remote:
    type: boolean
    default: false

commands:
  push-metrics-to-git:
    description: "Send Metrics to git"
    parameters:
      doc-location:
        type: string
        default: "docs/"
      file-name:
        type: string
    steps:
      - run:
          name: 'Add Metrics to git'
          command: |
            git pull
            mv /tmp/metrics.zip << parameters.doc-location >><< parameters.file-name >>
            git add << parameters.doc-location >><< parameters.file-name >>
            git commit -m "added << parameters.doc-location >><< parameters.file-name >>"

  extract-code-coverage:
    description: "Extract Code Coverage from the build"
    parameters:
      docker-file-location:
        type: string
      path-to-metrics:
        type: string
    steps:
      - run:
          name: 'Extract code coverage'
          command: |
            docker build -t temp_build -f "<< parameters.docker-file-location >>" "java" --target build
            docker create --name temp_container temp_build
            docker cp temp_container:<< parameters.path-to-metrics >> /tmp/
            docker rm temp_container

  build-docker:
    description: "Build Docker image"
    parameters:
      docker-repo:
        type: string
      docker-file-location:
        type: string
    steps:
      - run:
          name: 'Build Docker image'
          command: |
            docker build -t "<< parameters.docker-repo >>:latest" -f "<< parameters.docker-file-location >>" "java"

  push-docker-to-repo:
    description: "Push build to docker repo"
    parameters:
      docker-repo:
        type: string
    steps:
      - run:
          name: 'Push to repository'
          command: |
            docker login --username ${DOCKER_USER} --password ${DOCKER_PASSWORD}
            docker push "<< parameters.docker-repo >>:latest"

jobs:
  build-shared-utils:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - extract-code-coverage:
          docker-file-location: "java/sharedUtils/Dockerfile" 
          path-to-metrics: /app/sharedUtils/target/metrics.zip
      - store_artifacts:
          path: /tmp/metrics.zip
          destination: sharedUtils-metrics.zip
      - push-metrics-to-git:
          file-name: "sharedUtils-metrics.zip"

  build-db-importer:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - extract-code-coverage:
          docker-file-location: "java/dbImporter/Dockerfile" 
          path-to-metrics: /app/dbImporter/target/metrics.zip
      - build-docker:
          docker-repo: ${DOCKER_REPO_DB_IMPORTER}
          docker-file-location: "java/dbImporter/Dockerfile"
      - push-docker-to-repo:
          docker-repo: ${DOCKER_REPO_DB_IMPORTER}
      - store_artifacts:
          path: /tmp/metrics.zip
          destination: dbImporter-metrics.zip
      - push-metrics-to-git:
          file-name: "dbImporter-metrics.zip"

  build-light-bulb:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - extract-code-coverage:
          docker-file-location: "java/lightBulb/Dockerfile" 
          path-to-metrics: /app/lightBulb/target/metrics.zip
      - store_artifacts:
          path: /tmp/metrics.zip
          destination: lightBulb-metrics.zip
      - build-docker:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB}
          docker-file-location: "java/lightBulb/Dockerfile"
      - push-docker-to-repo:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB}
      - push-metrics-to-git:
          file-name: "lightBulb-metrics.zip"

  build-light-bulb-monitor:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - extract-code-coverage:
          docker-file-location: "java/lightBulbMonitor/Dockerfile" 
          path-to-metrics: /app/lightBulbMonitor/target/metrics.zip      
      - store_artifacts:
          path: /tmp/metrics.zip
          destination: lightBulbMonitor-metrics.zip
      - build-docker:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB_MONITOR}
          docker-file-location: "java/lightBulbMonitor/Dockerfile"
      - push-docker-to-repo:
          docker-repo: ${DOCKER_REPO_LIGHT_BULB_MONITOR}
      - push-metrics-to-git:
          file-name: "lightBulbMonitor-metrics.zip"

  build-remote:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - build-docker:
          docker-repo: ${DOCKER_REPO_REMOTE}
          docker-file-location: "java/remote/Dockerfile"
      - push-docker-to-repo:
          docker-repo: ${DOCKER_REPO_REMOTE}

workflows:
  workflow-build-shared-utils:
    when: << pipeline.parameters.param-build-shared-utils >>
    jobs:
      - build-shared-utils:
          context:
            - org-context-smart-home
  workflow-build-db-importer:
    when: << pipeline.parameters.param-build-db-importer >>
    jobs:
      - build-db-importer:
          context:
            - org-context-smart-home
  workflow-build-light-bulb:
    when: << pipeline.parameters.param-build-light-bulb >>
    jobs:
      - build-light-bulb:
          context:
            - org-context-smart-home
  workflow-build-light-bulb-monitor:
    when: << pipeline.parameters.param-build-light-bulb-monitor >>
    jobs:
      - build-light-bulb-monitor:
          context:
            - org-context-smart-home
  workflow-build-remote:
    when: << pipeline.parameters.param-build-remote >>
    jobs:
      - build-remote:
          context:
            - org-context-smart-home