version: 2.1

parameters:
  param-build-apps:
    type: boolean
    default: false
jobs:
  build-apps:
    machine:
      image: ubuntu-2204:current
    steps:
      - checkout
      - run: 
          name: Build apps
          command: ./scripts/circleci-build/build-images-circle.sh
      - run:
          name: Extract artifact from Docker image - dbImporter
          command: |
            docker create --name temp_container ${DOCKER_REPO}:db-importer-latest
            docker cp temp_container:/app/jacoco /tmp/jacoco-dbImporter
            docker rm temp_container
      - run:
          name: Extract artifact from Docker image - light-bulb-monitor
          command: |
            docker create --name temp_container_lbm ${DOCKER_REPO}:light-bulb-monitor-latest
            docker cp temp_container_lbm:/app/jacaco /tmp/jacoco-lightBulbMonitor
            docker rm temp_container_lbm
      - run:
          name: Extract artifact from Docker image - light-bulb
          command: |
            docker create --name temp_container_lb ${DOCKER_REPO}:light-bulb-latest
            docker cp temp_container_lb:/app/jacoco /tmp/jacoco-lightBulb
            docker rm temp_container_lb
      - store_artifacts:
          path: /tmp/jacoco-dbImporter
      - store_artifacts:
          path: /tmp/jacoco-lightBulbMonitor
      - store_artifacts:
          path: /tmp/jacoco-lightBulb
workflows:
  workflow-build-apps:
    when: << pipeline.parameters.param-build-apps >>
    jobs:
      - build-apps:
          context:
            - org-context-smart-home