{{- if .Values.lightMonitor.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-light-monitor-config
data:
{{ (.Files.Glob "raw-files/light-monitor/*.py").AsConfig | indent 2 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-light-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: light-monitor
  template:
    metadata:
      labels:
        app: light-monitor
    spec:
      containers:
        - name: light-monitor-container
          command:
            - "python"
            - "/app/main.py"
          image: {{ .Values.lightMonitor.image }}
          ports:
            - containerPort: {{ .Values.rabbitmq.port }}
          env:
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host }}
            - name: RABBITMQ_PORT
              value: "{{ .Values.rabbitmq.port }}"
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_PASS
              value: {{ .Values.rabbitmq.pass }}
            - name: RABBITMQ_QUEUE
              value: {{ .Values.lightMonitor.queue }}
          volumeMounts:
            - name: light-monitor-python
              mountPath: /app
      volumes:
        - name: light-monitor-python
          configMap:
            name: {{ .Release.Name }}-light-monitor-config
{{- end }}
