apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: busybox:latest
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
    resources: {}
    stdin: true
    tty: true
