# Name: dns-checker-yaml
# Description: A pod to check DNS on cluster, apply manually with
# kubectl apply -f dns-checker.yaml
# Author: ja-m3s
apiVersion: v1
kind: Pod
metadata:
  name: dnsutils
spec:
  containers:
  - name: dnsutils
    image: busybox:latest
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
    resources: {}
    stdin: true
    tty: true
