{{- if .Values.producer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer-container
          command:
            - "python"
            - "/app/producer.py"
          image: {{ .Values.producer.image }}
          ports:
            - containerPort: {{ .Values.producer.port }}
          env:
            - name: BOOTSTRAP_SERVERS
              value: {{ .Values.producer.bootstrapServers }}
            - name: TOPIC
              value: {{ .Values.producer.topic }}
          volumeMounts:
            - name: producer-python-config
              mountPath: /app
      volumes:
        - name: producer-python-config
          configMap:
            name: producer-python-config
{{- end }}