{
 "title": "Apps",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Importer (all requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "dbimporter_requests_received_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Light bulb monitor (all requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "lightbulbmonitor_requests_received_total",
     "legendFormat": "__auto"
    },
    {
     "expr": "lightbulbmonitor_requests_sent_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Light Bulbs (all requests)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "lightbulb_requests_received_total",
     "legendFormat": "__auto"
    },
    { "expr": "lightbulb_requests_sent_total", "legendFormat": "__auto" }
   ]
  }
 ]
}