apiVersion: v1
kind: Secret
metadata:
  name: database-password
type: Opaque
data:
  #generate a secure password before
  #applying the file with 
  #echo 'secure password of your choice' | base64
  password: cGFzc3dvcmQK