apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "name" . }}
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8082