# values.yaml

#shared values for rabbitmq
rabbitmq:
  host: event-bus-service
  port: "5672"  
  user: guest
  pass: guest

#shared values for database 
dbconf:
  dbUser: event_bus_connector
  dbUserPassword: password
  dbPort: "26257"
  dbName: db_smart_home
  dbSchema: s_smart_home
  #NB. release name is autoprepended to dbHost
  dbHost: cockroachdb-public.default.svc.cluster.local

eventBus:
  enabled: true
  image: rabbitmq:alpine

light:
  enabled: true
  numLights: 1

lightMonitor:
  enabled: true

dbImporter:
  enabled: true

cockroachClient:
  enabled: true
  image: cockroachdb/cockroach:v23.2.3

pythonConf:
  registry: localhost:32000
  image: python-custom:3.9.19-slim-bullseye