# values.yaml

#shared values for rabbitmq
rabbitmq:
  host: event-bus-service
  port: "5672"  
  user: guest
  pass: guest

#shared values for database 
dbconf:
  dbUser: event_bus_connector
  dbUserPassword: password
  dbPort: "26257"
  dbName: db_smart_home
  dbSchema: s_smart_home
  #NB. release name is autoprepended to dbHost
  dbHost: cockroachdb-public.default.svc.cluster.local

eventBus:
  enabled: true
  image: rabbitmq:management-alpine

lightBulb:
  enabled: true
  image: eclipse-temurin-light-bulb:21
  numLights: 1

lightBulbMonitor:
  enabled: false
  image: eclipse-temurin-light-bulb-monitor:21

dbImporter:
  enabled: false
  image: eclipse-temurin-db-importer:21

cockroachClient:
  enabled: false
  image: cockroachdb/cockroach:v23.2.3

registryConf:
  registry: localhost:32000
  