# values.yaml

#shared values for rabbitmq
rabbitmq:
  host: event-bus-service
  port: "5672"  
  user: guest
  pass: guest

#shared values for database 
dbconf:
  dbUser: event_bus_connector
  dbUserPassword: password
  dbPort: "26257"
  dbName: db_smart_home
  dbSchema: s_smart_home

dbImporter:
  enabled: true
  image: localhost:32000/python-custom:3.9.19-slim-bullseye
  queue: "topic_light"
  dbHost: cockroachdb-public.default.svc.cluster.local

eventBus:
  enabled: true
  image: rabbitmq:3.8

light:
  enabled: true
  image: localhost:32000/python-custom:3.9.19-slim-bullseye
  queue: "topic_light"

lightMonitor:
  enabled: true
  image: localhost:32000/python-custom:3.9.19-slim-bullseye
  queue: "topic_light"


##cockroach config
conf:
  cache: "500Mi"
  max-sql-memory: "500Mi"

cockroachImage: cockroachdb/cockroach:v23.2.3