# values.yaml

#shared values for rabbitmq
rabbitmq:
  host: rabbitmq
  port: "5672"  
  user: guest
  pass: guest

#shared values for database 
dbconf:
  dbUser: event_bus_connector
  dbUserPassword: password
  dbPort: "26257"
  dbName: db_smart_home
  dbSchema: s_smart_home
  #NB. release name is autoprepended to dbHost
  dbHost: cockroach-db-public.default.svc.cluster.local

eventBus:
  enabled: true
  image: rabbitmq:management-alpine

lightBulb:
  enabled: true
  image: smart-home-assistant:light-bulb-latest
  numLights: 3

lightBulbMonitor:
  enabled: true
  image: smart-home-assistant:light-bulb-monitor-latest

dbImporter:
  enabled: true
  image: smart-home-assistant:db-importer-latest

cockroachClient:
  enabled: true
  image: cockroachdb/cockroach:v23.2.3

#If unset, this will default to the local microk8s registry.
registryConf:
  registry: "dockerjam3s"
  