# values.yaml

#shared values for rabbitmq
rabbitmq:
  host: event-bus-service
  port: "5672"  
  user: guest
  pass: guest

#shared values for database 
dbconf:
  dbUser: event_bus_connector
  dbUserPassword: password
  dbPort: "5432"
  dbName: db_smart_home
  dbHost: database-service.default.svc.cluster.local

database:
  enabled: true
  image: postgres:latest
  postgresUserPassword: password

consumerDb:
  enabled: true
  image: localhost:32000/python-custom:latest
  queue: "topic_producer"

eventBus:
  enabled: true
  image: rabbitmq:3.8

producer:
  enabled: true
  image: localhost:32000/python-custom:latest
  queue: "topic_producer"

consumer:
  enabled: true
  image: localhost:32000/python-custom:latest
  queue: "topic_producer"