{{- if .Values.eventBus.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-event-bus-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
        - name: event-bus-server-container
          image: {{ .Values.eventBus.image }}
          ports:
            - name: port
              containerPort: {{ .Values.rabbitmq.port }}
{{- end }}